name: Generate Terraform Plan Change Report
author: gpuliyar
description: Set the generated Terraform Plan change report as a Pull Request comment
branding:
  icon: git-pull-request
  color: blue
inputs:
  file-name:
    description: JSON terraform report file name.
    required: true
    default: tfplan-show.json
runs:
  using: node16
  main: dist/index.js
